spring:
  config:
    activate:
      on-profile: default

mail:
  protocol: ${MAIL_PROTOCOL:smtp}
  host: ${MAIL_HOST:smtp.gmail.com}
  port: ${MAIL_PORT:587}
  username: ${MAIL_USERNAME:username}
  password: ${MAIL_PASSWORD:password}
