name: d-day-label
on:
  schedule:
    - cron: "0 15 * * *"
jobs:
  d-day-labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: d-day-label
        uses: naver/d-day-labeler@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
